// <!-- Vast majority of code GENERATED BY CHATGPT 5.2 on 3/2/26 -->
// Fixed date order: earliest -> latest (39 total)
const DATES = [
	// April (13)
	{ id: "apr-2", label: "2", month: "April", display: "Apr 2" },
	{ id: "apr-3", label: "3", month: "April", display: "Apr 3" },
	{ id: "apr-4", label: "4", month: "April", display: "Apr 4" },
	{ id: "apr-9", label: "9", month: "April", display: "Apr 9" },
	{ id: "apr-10", label: "10", month: "April", display: "Apr 10" },
	{ id: "apr-11", label: "11", month: "April", display: "Apr 11" },
	{ id: "apr-16", label: "16", month: "April", display: "Apr 16" },
	{ id: "apr-17", label: "17", month: "April", display: "Apr 17" },
	{ id: "apr-18", label: "18", month: "April", display: "Apr 18" },
	{ id: "apr-23", label: "23", month: "April", display: "Apr 23" },
	{ id: "apr-24", label: "24", month: "April", display: "Apr 24" },
	{ id: "apr-25", label: "25", month: "April", display: "Apr 25" },
	{ id: "apr-30", label: "30", month: "April", display: "Apr 30" },

	// May (14)
	{ id: "may-1", label: "1", month: "May", display: "May 1" },
	{ id: "may-2", label: "2", month: "May", display: "May 2" },
	{ id: "may-7", label: "7", month: "May", display: "May 7" },
	{ id: "may-8", label: "8", month: "May", display: "May 8" },
	{ id: "may-9", label: "9", month: "May", display: "May 9" },
	{ id: "may-14", label: "14", month: "May", display: "May 14" },
	{ id: "may-15", label: "15", month: "May", display: "May 15" },
	{ id: "may-16", label: "16", month: "May", display: "May 16" },
	{ id: "may-21", label: "21", month: "May", display: "May 21" },
	{ id: "may-22", label: "22", month: "May", display: "May 22" },
	{ id: "may-23", label: "23", month: "May", display: "May 23" },
	{ id: "may-28", label: "28", month: "May", display: "May 28" },
	{ id: "may-29", label: "29", month: "May", display: "May 29" },
	{ id: "may-30", label: "30", month: "May", display: "May 30" },

	// June (12)
	{ id: "jun-4", label: "4", month: "June", display: "Jun 4" },
	{ id: "jun-5", label: "5", month: "June", display: "Jun 5" },
	{ id: "jun-6", label: "6", month: "June", display: "Jun 6" },
	{ id: "jun-11", label: "11", month: "June", display: "Jun 11" },
	{ id: "jun-12", label: "12", month: "June", display: "Jun 12" },
	{ id: "jun-13", label: "13", month: "June", display: "Jun 13" },
	{ id: "jun-18", label: "18", month: "June", display: "Jun 18" },
	{ id: "jun-19", label: "19", month: "June", display: "Jun 19" },
	{ id: "jun-20", label: "20", month: "June", display: "Jun 20" },
	{ id: "jun-25", label: "25", month: "June", display: "Jun 25" },
	{ id: "jun-26", label: "26", month: "June", display: "Jun 26" },
	{ id: "jun-27", label: "27", month: "June", display: "Jun 27" },
];

const TOTAL_BITS = DATES.length; // 39
const HEX_DIGITS = 10; // ceil(39/4) = 10

// Blackout state (direct toggles)
const selected = new Array(TOTAL_BITS).fill(false);

// Summary state (list of {label, hex, valid, maskBigInt})
let entriesState = [];

// Mode
let mode = "blackout"; // "blackout" | "summary"

const el = (id) => document.getElementById(id);

function toast(msg, kind = "ok") {
	const t = el("toast");
	t.textContent = msg;
	t.className = "toast show " + (kind === "err" ? "err" : "ok");
	clearTimeout(toast._timer);
	toast._timer = setTimeout(() => {
		t.className = "toast";
	}, 1800);
}

// ---------- Rendering the date grid ----------
function makeDateButton(index) {
	const d = DATES[index];
	const btn = document.createElement("button");
	btn.type = "button";
	btn.className = "date-btn";
	btn.setAttribute("data-index", String(index));
	btn.setAttribute("title", d.display);

	// In blackout, it's interactive; in summary, it's display-only
	btn.setAttribute("aria-pressed", "false");
	btn.textContent = d.label;

	btn.addEventListener("click", () => {
		if (mode !== "blackout") return;
		selected[index] = !selected[index];
		btn.setAttribute("aria-pressed", selected[index] ? "true" : "false");
		updateBlackoutEncoding();
	});

	return btn;
}

function renderDates() {
	const apr = el("dates-apr");
	const may = el("dates-may");
	const jun = el("dates-jun");

	apr.innerHTML = "";
	may.innerHTML = "";
	jun.innerHTML = "";

	for (let i = 0; i < TOTAL_BITS; i++) {
		const btn = makeDateButton(i);
		if (DATES[i].month === "April") apr.appendChild(btn);
		else if (DATES[i].month === "May") may.appendChild(btn);
		else jun.appendChild(btn);
	}

	// Ensure correct visuals for current mode
	syncDateVisualState();
}

// ---------- Blackout encoding ----------
function encodeSelectedToHex(bitsBoolArray) {
	let mask = 0n;
	for (let i = 0; i < bitsBoolArray.length; i++) {
		if (bitsBoolArray[i]) mask |= 1n << BigInt(i);
	}
	let hex = mask.toString(16).padStart(HEX_DIGITS, "0");
	return "BLACKOUTx" + hex;
}

function countSelectedByMonth(month) {
	let c = 0;
	for (let i = 0; i < TOTAL_BITS; i++) {
		if (DATES[i].month === month && selected[i]) c++;
	}
	return c;
}

function updateBlackoutEncoding() {
	el("encoding").value = encodeSelectedToHex(selected);

	const total = selected.reduce((a, b) => a + (b ? 1 : 0), 0);
	el("selected-count").textContent = String(total);

	el("count-apr").textContent = String(countSelectedByMonth("April"));
	el("count-may").textContent = String(countSelectedByMonth("May"));
	el("count-jun").textContent = String(countSelectedByMonth("June"));
}

// ---------- Mode switching ----------
function setMode(nextMode) {
	mode = nextMode;

	// Toggle buttons
	el("mode-blackout").setAttribute(
		"aria-pressed",
		mode === "blackout" ? "true" : "false",
	);
	el("mode-summary").setAttribute(
		"aria-pressed",
		mode === "summary" ? "true" : "false",
	);

	// Show/hide panels
	el("summary-panel").classList.toggle("hidden", mode !== "summary");
	el("blackout-panel").classList.toggle("hidden", mode !== "blackout");

	// When entering summary, we should recompute highlights immediately
	syncDateVisualState();
	if (mode === "summary") recomputeSummaryCollisions();
	if (mode === "blackout") updateBlackoutEncoding();
}

function syncDateVisualState() {
	const buttons = document.querySelectorAll(".date-btn");
	const selectedCounts = document.getElementsByClassName("count selected");

	let blackoutModeActive = mode === "blackout";
	let summaryModeActive = !blackoutModeActive;

	for (let i = 0; i < buttons.length; i++) {
		const b = buttons[i];

		// disable pointer interaction in summary
		b.classList.toggle("disabled", summaryModeActive);

		// clear summary red state always, will be re-applied by summary logic
		b.classList.remove("hot");
		b.removeAttribute("data-collisions");

		// keep blackout selection visuals
		if (blackoutModeActive) {
			b.setAttribute("aria-pressed", selected[i] ? "true" : "false");
		} else {
			// summary mode: dates are not "pressed"
			b.setAttribute("aria-pressed", "false");
		}
	}

	// Only show monthly selected counts in blackout
	for (const el of selectedCounts) {
		el.hidden = !blackoutModeActive;
	}
}

// ---------- Summary mode UI ----------
function fillMaxAllowed() {
	const sel = el("max-allowed");
	sel.innerHTML = "";
	for (let i = 0; i <= 10; i++) {
		const opt = document.createElement("option");
		opt.value = String(i);
		opt.textContent = String(i);
		if (i === 0) opt.selected = true;
		sel.appendChild(opt);
	}
	sel.addEventListener("change", recomputeSummaryCollisions);
}

function addEntry(initialLabel = "", initialHex = "") {
	const entry = {
		id: crypto.randomUUID
			? crypto.randomUUID()
			: String(Date.now()) + Math.random(),
		label: initialLabel,
		hex: initialHex,
		valid: false,
		mask: null, // BigInt
	};
	entriesState.push(entry);
	renderEntries();
	recomputeSummaryCollisions();
}

function removeEntry(id) {
	entriesState = entriesState.filter((e) => e.id !== id);
	renderEntries();
	recomputeSummaryCollisions();
}

function normalizeHex(input) {
	// accept: "BLACKOUTx..."
	let s = String(input || "")
		.trim()
		.replace(/\s+/g, "");
	if (s.startsWith("BLACKOUTx")) {
		s = "0x" + s.slice(s.indexOf("x") + 1);
		return s;
	} else {
		return -1;
	}
}

function parseMaskHex(hexStr) {
	const s = normalizeHex(hexStr);

	// must be 0x + 1..10 hex digits (we'll allow shorter), but must not exceed 39 bits
	if (!/^0x[0-9a-fA-F]{1,10}$/.test(s))
		return { ok: false, normalized: s, mask: null };

	try {
		const mask = BigInt(s);
		if (mask < 0n) return { ok: false, normalized: s, mask: null };
		// Ensure no bits above 38
		const maxMask = (1n << BigInt(TOTAL_BITS)) - 1n;
		if (mask > maxMask) return { ok: false, normalized: s, mask: null };
		return {
			ok: true,
			normalized: "0x" + mask.toString(16).padStart(HEX_DIGITS, "0"),
			mask,
		};
	} catch {
		return { ok: false, normalized: s, mask: null };
	}
}

function pasteFromClipboardInto(id) {
	const input = document.querySelector(`[data-entry-id="${id}"] .hex-input`);

	navigator.clipboard
		.readText()
		.then((clipText) => {
			input.value = clipText;
			input.dispatchEvent(new Event("input", { bubbles: true }));
		})
		.catch((err) => toast("Clipboard paste failed.", err));
}

function renderEntries() {
	const container = el("entries");
	container.innerHTML = "";

	entriesState.forEach((entry) => {
		const row = document.createElement("div");
		row.className = "entry";
		row.setAttribute("data-entry-id", entry.id);

		row.innerHTML = `
      <div class="entry-grid">
        <div class="field">
          <label>Label</label>
          <input class="text-input" type="text" value="${escapeHtml(entry.label)}" placeholder="e.g. Steven" />
        </div>

        <div class="field grow">
          <label>Hex code</label>
          <div class="hex-row">
            <input class="hex-input mono" type="text" value="${escapeHtml(entry.hex)}" placeholder="BLACKOUTx0000000000" />
            <button class="btn" type="button" data-action="paste">Paste</button>
            <div class="validity" aria-label="validity">${entry.valid ? "✓" : entry.hex.trim() ? "✗" : ""}</div>
          </div>
        </div>

        <div class="field">
          <label>&nbsp;</label>
          <button class="btn danger" type="button" data-action="remove">Remove</button>
        </div>
      </div>
    `;

		// Wire events
		const labelInput = row.querySelector(".text-input");
		const hexInput = row.querySelector(".hex-input");
		const pasteBtn = row.querySelector('[data-action="paste"]');
		const removeBtn = row.querySelector('[data-action="remove"]');

		labelInput.addEventListener("input", () => {
			entry.label = labelInput.value;
		});

		hexInput.addEventListener("input", () => {
			entry.hex = hexInput.value;

			const parsed = parseMaskHex(entry.hex);
			entry.valid = parsed.ok;
			entry.mask = parsed.ok ? parsed.mask : null;

			// normalize display to padded canonical hex once valid (less surprise: do it on blur)
			const validity = row.querySelector(".validity");
			validity.textContent = entry.valid ? "✓" : entry.hex.trim() ? "✗" : "";

			recomputeSummaryCollisions();
		});

		hexInput.addEventListener("blur", () => {
			const parsed = parseMaskHex(entry.hex);
			if (parsed.ok) {
				entry.hex = parsed.normalized;
				hexInput.value = parsed.normalized;
			}
		});

		pasteBtn.addEventListener("click", () => pasteFromClipboardInto(entry.id));
		removeBtn.addEventListener("click", () => removeEntry(entry.id));

		container.appendChild(row);
	});

	if (entriesState.length === 0) {
		const empty = document.createElement("div");
		empty.className = "empty";
		empty.textContent = "No entries yet. Tap “Add person”.";
		container.appendChild(empty);
	}
}

function escapeHtml(s) {
	return String(s ?? "")
		.replaceAll("&", "&amp;")
		.replaceAll("<", "&lt;")
		.replaceAll(">", "&gt;")
		.replaceAll('"', "&quot;")
		.replaceAll("'", "&#039;");
}

// ---------- Summary collision computation ----------
function recomputeSummaryCollisions() {
	if (mode !== "summary") return;

	const maxAllowed = Number(el("max-allowed").value || "0");

	// collisions[i] = number of valid masks with bit i set
	const collisions = new Array(TOTAL_BITS).fill(0);

	for (const entry of entriesState) {
		if (!entry.valid || entry.mask == null) continue;
		const m = entry.mask;

		for (let i = 0; i < TOTAL_BITS; i++) {
			if ((m >> BigInt(i)) & 1n) collisions[i] += 1;
		}
	}

	// Paint dates: if collisions[i] > maxAllowed, show as "selected" but red (hot)
	const buttons = document.querySelectorAll(".date-btn");
	for (let i = 0; i < buttons.length; i++) {
		const c = collisions[i];
		const hot = c > maxAllowed && c > 0;

		buttons[i].classList.toggle("hot", hot);
		buttons[i].setAttribute("data-collisions", c ? String(c) : "");
	}
}

// ---------- Clipboard for blackout ----------
async function copyEncoding() {
	const text = el("encoding").value;
	try {
		if (navigator.clipboard && window.isSecureContext) {
			await navigator.clipboard.writeText(text);
		} else {
			el("encoding").focus();
			el("encoding").select();
			document.execCommand("copy");
		}
		toast("Copied to clipboard.");
	} catch {
		toast("Copy failed. Tap and hold to copy manually.", "err");
	}
}

function setAllBlackout(value) {
	if (mode !== "blackout") return;
	const buttons = document.querySelectorAll(".date-btn");
	for (let i = 0; i < TOTAL_BITS; i++) {
		selected[i] = value;
		buttons[i].setAttribute("aria-pressed", value ? "true" : "false");
	}
	updateBlackoutEncoding();
}

document.addEventListener("DOMContentLoaded", () => {
	// dates
	renderDates();

	// blackout actions
	el("select-all").addEventListener("click", () => setAllBlackout(true));
	el("clear-all").addEventListener("click", () => setAllBlackout(false));
	el("copy").addEventListener("click", copyEncoding);
	updateBlackoutEncoding();

	// mode toggles
	el("mode-blackout").addEventListener("click", () => setMode("blackout"));
	el("mode-summary").addEventListener("click", () => setMode("summary"));

	// summary setup
	fillMaxAllowed();
	el("add-entry").addEventListener("click", () => addEntry("", ""));

	// start with one entry by default (nice UX)
	addEntry("", "");
});
