// <!-- GENERATED BY CHATGPT 5.2 on 3/2/26 -->
// Fixed date order: earliest -> latest (39 total)
const DATES = [
	// April (13)
	{ id: "apr-2", label: "2", month: "April", display: "Apr 2" },
	{ id: "apr-3", label: "3", month: "April", display: "Apr 3" },
	{ id: "apr-4", label: "4", month: "April", display: "Apr 4" },
	{ id: "apr-9", label: "9", month: "April", display: "Apr 9" },
	{ id: "apr-10", label: "10", month: "April", display: "Apr 10" },
	{ id: "apr-11", label: "11", month: "April", display: "Apr 11" },
	{ id: "apr-16", label: "16", month: "April", display: "Apr 16" },
	{ id: "apr-17", label: "17", month: "April", display: "Apr 17" },
	{ id: "apr-18", label: "18", month: "April", display: "Apr 18" },
	{ id: "apr-23", label: "23", month: "April", display: "Apr 23" },
	{ id: "apr-24", label: "24", month: "April", display: "Apr 24" },
	{ id: "apr-25", label: "25", month: "April", display: "Apr 25" },
	{ id: "apr-30", label: "30", month: "April", display: "Apr 30" },

	// May (14) — note: May has 14 dates in your list
	{ id: "may-1", label: "1", month: "May", display: "May 1" },
	{ id: "may-2", label: "2", month: "May", display: "May 2" },
	{ id: "may-7", label: "7", month: "May", display: "May 7" },
	{ id: "may-8", label: "8", month: "May", display: "May 8" },
	{ id: "may-9", label: "9", month: "May", display: "May 9" },
	{ id: "may-14", label: "14", month: "May", display: "May 14" },
	{ id: "may-15", label: "15", month: "May", display: "May 15" },
	{ id: "may-16", label: "16", month: "May", display: "May 16" },
	{ id: "may-21", label: "21", month: "May", display: "May 21" },
	{ id: "may-22", label: "22", month: "May", display: "May 22" },
	{ id: "may-23", label: "23", month: "May", display: "May 23" },
	{ id: "may-28", label: "28", month: "May", display: "May 28" },
	{ id: "may-29", label: "29", month: "May", display: "May 29" },
	{ id: "may-30", label: "30", month: "May", display: "May 30" },

	// June (12) — note: June has 12 dates in your list
	{ id: "jun-4", label: "4", month: "June", display: "Jun 4" },
	{ id: "jun-5", label: "5", month: "June", display: "Jun 5" },
	{ id: "jun-6", label: "6", month: "June", display: "Jun 6" },
	{ id: "jun-11", label: "11", month: "June", display: "Jun 11" },
	{ id: "jun-12", label: "12", month: "June", display: "Jun 12" },
	{ id: "jun-13", label: "13", month: "June", display: "Jun 13" },
	{ id: "jun-18", label: "18", month: "June", display: "Jun 18" },
	{ id: "jun-19", label: "19", month: "June", display: "Jun 19" },
	{ id: "jun-20", label: "20", month: "June", display: "Jun 20" },
	{ id: "jun-25", label: "25", month: "June", display: "Jun 25" },
	{ id: "jun-26", label: "26", month: "June", display: "Jun 26" },
	{ id: "jun-27", label: "27", month: "June", display: "Jun 27" },
];

// NOTE:
// Your original spec says 39 dates total. The list you provided is:
// April 13 + May 14 + June 12 = 39. ✅

const selected = new Array(DATES.length).fill(false);

const el = (id) => document.getElementById(id);

function toast(msg, kind = "ok") {
	const t = el("toast");
	t.textContent = msg;
	t.className = "toast show " + (kind === "err" ? "err" : "ok");
	clearTimeout(toast._timer);
	toast._timer = setTimeout(() => {
		t.className = "toast";
	}, 1800);
}

function makeButton(index) {
	const d = DATES[index];
	const btn = document.createElement("button");
	btn.type = "button";
	btn.className = "date-btn";
	btn.setAttribute("data-index", String(index));
	btn.setAttribute("aria-pressed", "false");
	btn.setAttribute("title", d.display);
	btn.textContent = d.label;

	btn.addEventListener("click", () => {
		selected[index] = !selected[index];
		btn.setAttribute("aria-pressed", selected[index] ? "true" : "false");
		updateEncoding();
	});

	return btn;
}

function render() {
	const apr = el("dates-apr");
	const may = el("dates-may");
	const jun = el("dates-jun");

	for (let i = 0; i < DATES.length; i++) {
		const btn = makeButton(i);
		if (DATES[i].month === "April") apr.appendChild(btn);
		else if (DATES[i].month === "May") may.appendChild(btn);
		else jun.appendChild(btn);
	}

	updateEncoding();
}

// Encode selected[] into hex for a 39-bit integer mask.
// bit i = 1 if date i selected
function encodeToHex() {
	let mask = 0n;
	for (let i = 0; i < selected.length; i++) {
		if (selected[i]) mask |= 1n << BigInt(i);
	}
	// 39 bits -> ceil(39/4)=10 hex digits
	const hexDigits = 10;
	let hex = mask.toString(16).padStart(hexDigits, "0");
	return "0x" + hex;
}

function countByMonth(month) {
	let c = 0;
	for (let i = 0; i < DATES.length; i++) {
		if (DATES[i].month === month && selected[i]) c++;
	}
	return c;
}

function updateEncoding() {
	el("encoding").value = encodeToHex();

	const total = selected.reduce((a, b) => a + (b ? 1 : 0), 0);
	el("selected-count").textContent = String(total);

	el("count-apr").textContent = String(countByMonth("April"));
	el("count-may").textContent = String(countByMonth("May"));
	el("count-jun").textContent = String(countByMonth("June"));
}

function setAll(value) {
	const buttons = document.querySelectorAll(".date-btn");
	for (let i = 0; i < selected.length; i++) {
		selected[i] = value;
		buttons[i].setAttribute("aria-pressed", value ? "true" : "false");
	}
	updateEncoding();
}

async function copyEncoding() {
	const text = el("encoding").value;
	try {
		if (navigator.clipboard && window.isSecureContext) {
			await navigator.clipboard.writeText(text);
		} else {
			// fallback
			el("encoding").focus();
			el("encoding").select();
			document.execCommand("copy");
		}
		toast("Copied to clipboard.");
	} catch {
		toast("Copy failed. Tap and hold to copy manually.", "err");
	}
}

document.addEventListener("DOMContentLoaded", () => {
	el("select-all").addEventListener("click", () => setAll(true));
	el("clear-all").addEventListener("click", () => setAll(false));
	el("copy").addEventListener("click", copyEncoding);
	render();
});
